# Generated by Django 2.0.2 on 2018-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180226_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
